---
title: "YuanChen_DC17"
author: "Yuan Chen"
date: '2022-11-15'
output: html_document
---
### STAT 184 Homework Exercises

##  Data Computing Chapter 11

Yuan Chen

##  Assign Exercises 

17.1 (part 1 & 3), 17.4 (part 1 & 2),  17.5

```{r}
library(dplyr)
library(ggplot2)
library(dygraphs)
library(ggplot2)
library(dcData)
data("BabyNames", package = "dcData")
```
## problem 17.1(part 1 & 3)

```{r}
NameList <- 
  BabyNames %>% 
  group_by(name, sex) %>%
  summarise(total = sum(count)) %>%
  arrange(desc(total)) 
NameList %>% 
  filter(grepl("[aeiou]$", name, ignore.case = TRUE) ) 
NameList %>% 
  filter(grepl("joe$", name, ignore.case = TRUE) ) 
```


## problem 17.4(part 1 & 2)
1. the string will be maximum of 2 character.
2. The total is  = 7+3+2+2+2+1+4+2+1+10+8+3+3+1+2+2+1+3+4 = 61


## problem 17.5
in the name
```{r}
BibleNames <- 
  readr::read_csv("https://mdbeckman.github.io/dcSupplement/data/BibleNames.csv")
BibleNames%>%
  filter(grepl( "bar", name, ignore.case = TRUE))
BibleNames%>%
  filter(grepl( "dam",name, ignore.case = TRUE))
BibleNames%>%
  filter(grepl( "lory",name, ignore.case = TRUE))
```
end in the name
```{r}
BibleNames%>%
  filter(grepl( "bar$", name, ignore.case = TRUE))
BibleNames%>%
  filter(grepl( "dam$",name, ignore.case = TRUE))
BibleNames%>%
  filter(grepl( "lory$",name, ignore.case = TRUE))
```







